name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Node.js setup and steps
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Node.js dependencies
      run: npm install

    - name: Run Node.js tests
      run: npm test

    - name: Build Node.js project
      run: npm run build

    # Qt/C++ setup and steps
    - name: Install Qt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qtbase5-dev qt5-qmake xvfb

    - name: Build and test 'loginpage_test'
      run: |
        cd loginpage_test
        qmake loginpage_test.pro
        make
        xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' ./loginpage_test
