name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:  # Combined build and test job (optional)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make

      - name: Install Qt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qtbase5-dev qt5-qmake xvfb

      - name: Build project
        run: |
          mkdir build  # Create build directory
          cd build
          cmake ..  # Configure build using CMakelists.txt
          make       # Build the project

      - name: Run loginpage_test
        working-directory: loginpage_test  # Change directory to test directory
        run: |
          qmake loginpage_test.pro  # Generate Makefile using QMake
          make                       # Build the loginpage_test executable
          xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' ./loginpage_test  # Run the test with Xvfb for display

